### ISSUE TITLE
Background color for refresh

### ISSUE THREAD

**Issue by dannydaddy3** [xorshine/KafkaRefresh#10]
If I got right I can set background color only with singleton. 
But in my project I use refreshes on different screens, so choosing one background color for all screens is not suited for me because screens have different background colors. 
Changing color in singleton as I switch between screens is obviously kludge.

Would be good to add new method with `backgroundColor` property or add this property to current method. So it could be possible to set color at refresh creation.

**Comment by xorshine** [comment]
Please update the library in three hours and you can see a new addition to animateBackgroundColor
