### ISSUE TITLE
当设置导航栏为透明时，下拉动画会失效

### ISSUE THREAD

**Issue by daiyangyang945** [xorshine/KafkaRefresh#14]
只有当push到下一个controller时才会出现这个问题，我用的是KafkaRefreshStyleAnimatableRing
![img_2621 20180125-174316](https://user-images.githubusercontent.com/26043410/35381575-b77eddf4-01f7-11e8-81bf-8062a6e19fdf.jpg)

**Comment by xorshine** [comment]
明天中午更新新版本，请更新即可

**Comment by xorshine** [comment]
请更新
