### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by luhuafei** [xorshine/KafkaRefresh#17]
上拉加载更多, 如果所有的数据都被加载完了, 怎样设置, "已经加载完毕", 类似mjrefresh的endRefreshingWithNoMoreData

**Comment by xorshine** [comment]
谢谢。
这是一个很好的提议。
我会在今晚将这个功能加上。

**Comment by luhuafei** [comment]
大佬, 辛苦

**Comment by xorshine** [comment]
+ version:0.9.6

- (void)endRefreshingAndNoLongerRefreshingWithAlertText:(NSString *)text;

**Comment by BinBear** [comment]
@xorshine
 (void)endRefreshingAndNoLongerRefreshingWithAlertText:(NSString *)text 这个API可以实现已经加载完毕了，可是当重新下拉刷新的时候，没法重置上拉的状态

**Comment by BinBear** [comment]
@xorshine 当我上拉加载更多，已经加载了全部的数据，这个时候我不需要刷新功能了。可是我再次下拉刷新的时候，要重置上拉状态，这个时候上拉刷新已经被禁止，没法操作了

**Comment by BinBear** [comment]
@xorshine 就是类似MJ里面resetNoMoreData的操作

**Comment by xorshine** [comment]
版本 1.0.2

- (void)resumeRefreshAvailable;

**Comment by HMWDavid** [comment]
resumeRefreshAvailable 之后 UIActivityIndi​​catorView 好像没有隐藏
