### ISSUE TITLE
更改加载成功后的文字颜色以及动画背景颜色

### ISSUE THREAD

**Issue by BinBear** [xorshine/KafkaRefresh#18]
作者您好：
endRefreshingWithAlertText:@"did load successfully"
我在加载完成的时候，调用headRefreshControl上面的方法，请问一下，我该如何更改文字的颜色以及动画背景颜色

**Comment by xorshine** [comment]
文字颜色及背景色都将依据刷新控件的fillColor，没有开放该接口。设计本意，是为了颜色和背景色能够与刷新控件的fillColor一致。

**Comment by xorshine** [comment]
0.9.7  开放setAlertTextColor: 接口。
但没有开放背景色，我希望这个库的风格能是自己喜欢的风格
