### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by BinBear** [xorshine/KafkaRefresh#19]
您好：
![image](https://user-images.githubusercontent.com/13587915/35725332-f3fda7de-083b-11e8-858c-c34ab42c2961.png)
当我调用endRefreshingWithAlertText:传入的title为国际化适配的title时，加载完成的动画不显示了，把title直接传入为@"刷新成功"时，动画就可以显示

**Comment by BinBear** [comment]
经过测试后，发现不是国际化的问题，是title传入中文就不显示动画，传入英文就可以，你的Demo也是这样

**Comment by xorshine** [comment]
Demo中使用中文进行测试，未重现你的问题。请告知更详细的步骤

```
[self.tableView bindRefreshStyle:_style
						   fillColor:MainColor
						  atPosition:1 refreshHanler:^{
							  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
			[weakSelf.source addObjectsFromArray:@[@"",@"",@"",@"",@"",@""]]; 
			  [weakSelf.tableView.footRefreshControl endRefreshingWithAlertText:NSLocalizedString(@"架子啊山山水水说上", nil) completion:^{
				  [weakSelf.tableView reloadData];
			  }]; 
		});
	}];

```

**Comment by BinBear** [comment]
我下载了最新的Demo,在KafkaTableViewController.m中修改了如下代码，headRefreshControl调用endRefreshingWithAlertText，就可以重现这个
![image](https://user-images.githubusercontent.com/13587915/35726962-8ecaccf6-0841-11e8-9e9b-5c18666cf05e.png)

**Comment by xorshine** [comment]
我将代码使用中文进行测试，没有发现问题。请问是什么动画不显示？能否录屏上传

<img width="688" alt="2018-02-02 18 34 56" src="https://user-images.githubusercontent.com/16265582/35728837-d33fe8fc-0847-11e8-9240-2e697fb12d09.png">

**Comment by BinBear** [comment]
![img_0102](https://user-images.githubusercontent.com/13587915/35729809-dd335ea4-084a-11e8-85fc-c714b5c73e12.PNG)
![img_0103](https://user-images.githubusercontent.com/13587915/35729810-dd61bcfe-084a-11e8-9806-e4c3cf682ef6.PNG)
如上图，中文的时候，_alertLabel的CAGradientLayer不显示，但是英文的时候可以，模拟器，真机都试了，系统为ios11.2

**Comment by xorshine** [comment]
谢谢提出。居然没有注意到。
我会在周日解决该问题。

**Comment by BinBear** [comment]
@xorshine 你能告诉我大概问题出在哪里，怎么解决？因为明天项目要上线了，很急

**Comment by xorshine** [comment]
今天中午前解决。
并没有找到原因。这是很诡异的bug

**Comment by xorshine** [comment]
已修复。请在10点左右最新版本。
