### ISSUE TITLE
下拉刷新，tableview没有回到原来位置

### ISSUE THREAD

**Issue by zengjinzong** [xorshine/KafkaRefresh#2]
下拉刷新进行中时，多次下拉tableview之后，tableview没有回到初始位置，结束后最后停留在如下图位置。
![img_2055](https://user-images.githubusercontent.com/13520124/34661558-7e3e2e70-f485-11e7-81ef-0829f41dfde0.PNG)

**Comment by ProtonShell** [comment]
的确有,貌似是下拉刷新的时候没有判断当前的状态?

**Comment by xorshine** [comment]
很感谢提交的问题。已经修复。

**Comment by BinBear** [comment]
@xorshine 最新版还是会有这个问题，当正在下拉刷新的时候，继续下拉，tableview不会回到之前的位置

**Comment by xorshine** [comment]
版本1.0.0.你再试试
