### ISSUE TITLE
headRefreshControl设置backgroundColor

### ISSUE THREAD

**Issue by BinBear** [xorshine/KafkaRefresh#20]
headRefreshControl设置backgroundColor之后，tableView的背景颜色为白色，当headRefreshControl.backgroundColor不为白色时候，下拉的时候，会出现白色的view闪动一下

**Comment by xorshine** [comment]
白色闪动已修复，渐进出现。
但背景为白色是默认的，也不打算开放该接口。渐变色置于白色背景下才有较好的视觉效果。
