### ISSUE TITLE
正在刷新时，继续下拉，tableView没有回到之前的位置

### ISSUE THREAD

**Issue by BinBear** [xorshine/KafkaRefresh#22]
![image](https://user-images.githubusercontent.com/13587915/36036541-1a22aa04-0df5-11e8-9b3a-8609d85ad8a9.png)
![image](https://user-images.githubusercontent.com/13587915/36036549-1e705f20-0df5-11e8-9900-d02ce79812c2.png)
当正在刷新时，继续下拉，多次下拉，UITableView没有回到之前的位置，而且一直重复这个操作，tableView的位置会越来越下

**Comment by BinBear** [comment]
最新版本还是有这个问题

**Comment by xorshine** [comment]
1.0.0. 是这个版本吗
