### ISSUE TITLE
刷新中的一个小问题

### ISSUE THREAD

**Issue by biqinglin** [xorshine/KafkaRefresh#23]
比如下拉刷新，当我并没有下拉太多距离，也就是刷新的动画还未看见的时候，已经在执行刷新动作了，然后list回到初始位置，这个过程list移动的距离其实很小，这个地方我觉得不太好[http://or7w4dvn2.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6.mov](url)
具体看我录制的视频
这只是一个小小的建议~勿喷

**Comment by xorshine** [comment]
谢谢。
链接无法打开，还未明白你测意思。

**Comment by biqinglin** [comment]
http://or7w4dvn2.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6.mov

**Comment by biqinglin** [comment]
http://or7w4dvn2.bkt.clouddn.com/%E5%88%B7%E6%96%B0.mov

**Comment by xorshine** [comment]
该问题在我的测试中未出现过。也请尝试替换其他刷新库进行测试，排除自身的代码问题，若其他库正常，请告知详细的重现步骤以及版本号，将立刻解决。
