### ISSUE TITLE
发现一个小问题 不知道是不是我运用的不对

### ISSUE THREAD

**Issue by qingweiiOS** [xorshine/KafkaRefresh#24]
表现形式
当我的contentSize （高度）小于 frame（高度） 时  下拉并不会触发刷新

MJ 的可以

**Comment by qingweiiOS** [comment]
还有个问题  当我
[self.tableView.headRefreshControl beginRefreshing];
    [self.tableView.headRefreshControl beginRefreshing];
    [self.tableView.headRefreshControl beginRefreshing];
连续手动执行多次 beginRefreshing
表格的 内容   会下移 连续执行的越多 下移的距离越远

**Comment by xorshine** [comment]
请告知版本号。最新版本号为1.0.0
第一个问题在测试中没有发现。
第二个问题确实存在，谢谢指出，已经修复，请更新版本1.0.1
