### ISSUE TITLE
您好！请问考虑年后换工作吗？

### ISSUE THREAD

**Issue by xhzengAIB** [xorshine/KafkaRefresh#4]
https://github.com/xhzengAIB/jobs

Jack

**Comment by xorshine** [comment]
一年半前就想着某一天我要去阿里巴巴。
你们好优秀，我怀着最好的诚意。
此时的我，功底不足。
该在技术道路上走的更远，沉淀更多，才有资格回复“我要试试”。
谢谢。

**Comment by xhzengAIB** [comment]
你太谦虚了，我的微信：15915895880，我们来聊聊

**Comment by AAChartModel** [comment]
Alibaba 的招聘形式现在已经这么潮了?😊
