### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mahailin** [xorshine/KafkaRefresh#7]
1、KafkaReplicatorLayer类里，建议把图层相关的位置居中处理，目前是不居中的(比如点动画，将self.replicatorLayer.frame、self.replicatorLayer.instanceTransform处理下就可以了)；
2、上拉加载时，建议添加拉到底部时放开就可以加载，目前是拉到一定的偏移量后放开加载。

**Comment by xorshine** [comment]
谢谢
1、关于拉动的偏移量，暴露量相关属性，可以自定义；
2、关于居中，得空量，改改。
