### ISSUE TITLE
Public layer and view extensions 

### ISSUE THREAD

**Issue by dannydaddy3** [xorshine/KafkaRefresh#9]
The thing is when I tested component I got conflict with your extension properties for UIView and CALayer and mines. I have almost the same implementation of the extensions in my app, and I think that many projects have them implemented as well. 

So this conflict doesn't allow me to use you component, it worked only after I replaced imports of this extensions from .h to .m files:
#import "CALayer+KafkaLayout.h"
#import "UIView+KafkaLayout.h"
And removed them from umbrella list in pods project. 

I think that this extensions is good for internal use for your component and would be good if they do not affected other projects.

**Comment by xorshine** [comment]
谢谢提交的这个问题，由于我将这个扩展文件暴露出来。现在已修复，请再稍后尝试更新这个库
